/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Adriana
 */
public class Menu extends javax.swing.JFrame {

    private Control.GrafoDirigido grafo;
    private PanelGrafo panelGrafo;
    private javax.swing.JFrame ventanaGrafo;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        grafo = new Control.GrafoDirigido(new EDD.TablaHash());
        panelGrafo = new PanelGrafo();

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (ventanaGrafo == null) {
                    ventanaGrafo = new javax.swing.JFrame("Visualizador SynapseLogic");
                    ventanaGrafo.setSize(800, 600);
                    ventanaGrafo.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
                    
                    panelGrafo.setBackground(new java.awt.Color(245, 247, 250));
                    ventanaGrafo.add(panelGrafo);
                }
                
                panelGrafo.setGrafo(grafo);
                
           
                ventanaGrafo.setLocationRelativeTo(null); 
                ventanaGrafo.setVisible(true);
            }
});

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (grafo.getNodos().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Primero carga una red.");
                    return;
                }
                String origen = javax.swing.JOptionPane.showInputDialog("ID neurona origen:");
                if (origen == null || origen.trim().isEmpty()) return;
                String destino = javax.swing.JOptionPane.showInputDialog("ID neurona destino:");
                if (destino == null || destino.trim().isEmpty()) return;

                EDD.Lista<String> ruta = grafo.dijkstra(origen.trim(), destino.trim());
                if (ruta.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "No hay camino entre esas neuronas.");
                } else {
                    String resultado = "Ruta mas rapida:\n";
                    EDD.NodoLista<String> aux = ruta.getHead();
                    while (aux != null) {
                        resultado += aux.dato;
                        if (aux.pNext != null) resultado += " -> ";
                        aux = aux.pNext;
                    }
                    javax.swing.JOptionPane.showMessageDialog(null, resultado);
                }
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (grafo.getNodos().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Primero carga una red.");
                    return;
                }
                grafo.simularDeterioro();
                panelGrafo.repaint();
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Deterioro simulado. Los coeficientes k aumentaron un 20%.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        BtnCargar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel9.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(255, 153, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 205, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Selecciona una opcion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 270, 42));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cargar Diccionario de Neurotransmisores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 190, -1, -1));

        BtnCargar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCargar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargar.setText("Cargar Red Sinaptica (CSV)");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 133, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Mostrar Grafo");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 133, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Simular Deterioro Cognitivo por Fatiga");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 250, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Detectar Zonas Aisladas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 310, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Simular Flujo de Señal (Dijkstra)");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 310, -1, -1));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modificar Red");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 399, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("para continuar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 327, 42));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 360, 220));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 60, 360, 220));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel7.setText("jLabel5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 270, 360, 220));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel8.setText("jLabel5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 360, 220));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/fonfo2.png"))); // NOI18N
        jLabel10.setText("jLabel5");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 240, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
        if (!grafo.getNodos().isEmpty()) {
            int resp = javax.swing.JOptionPane.showConfirmDialog(this,
                "Ya hay datos cargados. ¿Desea reemplazarlos?", "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION);
            if (resp != javax.swing.JOptionPane.YES_OPTION) return;
            grafo = new Control.GrafoDirigido(grafo.getDiccionarioNeuroT());
        }
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        int resultado = selector.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                String ruta = selector.getSelectedFile().getAbsolutePath();
                grafo.cargarRedCSV(ruta);
                panelGrafo.setGrafo(grafo);
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Red cargada con " + grafo.getNodos().getSize() + " neuronas.");
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BtnCargarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        int resultado = selector.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                String ruta = selector.getSelectedFile().getAbsolutePath();
                grafo.cargarDiccionarioCSV(ruta);
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Diccionario cargado: " + grafo.getDiccionarioNeuroT().getCantidadElementos() + " neurotransmisores.");
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (grafo.getNodos().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero carga una red.");
            return;
        }
        String fuente = javax.swing.JOptionPane.showInputDialog(this, "Ingresa el ID de la neurona fuente:");
        if (fuente == null || fuente.trim().isEmpty()) return;
        fuente = fuente.trim();

        if (grafo.buscarNeurona(fuente) == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "La neurona '" + fuente + "' no existe.");
            return;
        }

        EDD.Lista<String> zonasAisladas = grafo.detectarZonasAisladas(fuente);
        panelGrafo.setAisladas(zonasAisladas);
        if (ventanaGrafo != null) ventanaGrafo.repaint();

        String mensaje;
        if (zonasAisladas.isEmpty()) {
            mensaje = "No hay zonas aisladas desde '" + fuente + "'.";
        } else {
            mensaje = "Zonas aisladas desde '" + fuente + "':\n";
            EDD.NodoLista<String> aux = zonasAisladas.getHead();
            while (aux != null) {
                mensaje += "- " + aux.dato + "\n";
                aux = aux.pNext;
            }
        }
        boolean conexo = grafo.verificarFuerteConexidad();
        mensaje += "\nEl grafo es fuertemente conexo: " + (conexo ? "Si" : "No");
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String[] opciones = {"Agregar Neurona", "Eliminar Neurona", "Agregar Sinapsis", "Eliminar Sinapsis"};
        String opcion = (String) javax.swing.JOptionPane.showInputDialog(this,
            "Selecciona una opcion:", "Modificar Red",
            javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (opcion == null) return;

        if (opcion.equals("Agregar Neurona")) {
            String id = javax.swing.JOptionPane.showInputDialog(this, "ID de la nueva neurona:");
            if (id == null || id.trim().isEmpty()) return;
            String kStr = javax.swing.JOptionPane.showInputDialog(this, "Coeficiente k (ejemplo: 1.0):");
            if (kStr == null) return;
            try {
                double k = Double.parseDouble(kStr.trim());
                grafo.agregarNeurona(id.trim(), k);
                panelGrafo.setGrafo(grafo);
                javax.swing.JOptionPane.showMessageDialog(this, "Neurona '" + id.trim() + "' agregada.");
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "El valor de k no es valido.");
            }

        } else if (opcion.equals("Eliminar Neurona")) {
            String id = javax.swing.JOptionPane.showInputDialog(this, "ID de la neurona a eliminar:");
            if (id == null || id.trim().isEmpty()) return;
            grafo.eliminarNeurona(id.trim());
            panelGrafo.setGrafo(grafo);
            javax.swing.JOptionPane.showMessageDialog(this, "Neurona eliminada.");

        } else if (opcion.equals("Agregar Sinapsis")) {
            String origen = javax.swing.JOptionPane.showInputDialog(this, "ID neurona origen:");
            if (origen == null || origen.trim().isEmpty()) return;
            String destino = javax.swing.JOptionPane.showInputDialog(this, "ID neurona destino:");
            if (destino == null || destino.trim().isEmpty()) return;
            String dStr = javax.swing.JOptionPane.showInputDialog(this, "Distancia:");
            if (dStr == null) return;
            String nt = javax.swing.JOptionPane.showInputDialog(this, "ID Neurotransmisor:");
            if (nt == null) return;
            String kStr = javax.swing.JOptionPane.showInputDialog(this, "Coeficiente k:");
            if (kStr == null) return;
            try {
                double dist = Double.parseDouble(dStr.trim());
                double k = Double.parseDouble(kStr.trim());
                grafo.agregarArista(origen.trim(), destino.trim(), dist, nt.trim(), k);
                panelGrafo.setGrafo(grafo);
                javax.swing.JOptionPane.showMessageDialog(this, "Sinapsis agregada.");
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Valor numerico no valido.");
            }

        } else if (opcion.equals("Eliminar Sinapsis")) {
            String origen = javax.swing.JOptionPane.showInputDialog(this, "ID neurona origen:");
            if (origen == null || origen.trim().isEmpty()) return;
            String destino = javax.swing.JOptionPane.showInputDialog(this, "ID neurona destino:");
            if (destino == null || destino.trim().isEmpty()) return;
            grafo.eliminarArista(origen.trim(), destino.trim());
            panelGrafo.setGrafo(grafo);
            javax.swing.JOptionPane.showMessageDialog(this, "Sinapsis eliminada.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
